# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: res_message.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='res_message.proto',
  package='MyMessage',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=b'\n\x11res_message.proto\x12\tMyMessage\"\x9a\x01\n\tDetectRes\x12\x10\n\x08\x66rame_id\x18\x01 \x02(\t\x12\x18\n\x10measurement_time\x18\x02 \x02(\x01\x12\x11\n\tleft_topx\x18\x03 \x02(\x05\x12\x11\n\tleft_topy\x18\x04 \x02(\x05\x12\x15\n\rright_bottomx\x18\x05 \x02(\x05\x12\x15\n\rright_bottomy\x18\x06 \x02(\x05\x12\r\n\x05score\x18\x07 \x02(\x01'
)




_DETECTRES = _descriptor.Descriptor(
  name='DetectRes',
  full_name='MyMessage.DetectRes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='frame_id', full_name='MyMessage.DetectRes.frame_id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='measurement_time', full_name='MyMessage.DetectRes.measurement_time', index=1,
      number=2, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='left_topx', full_name='MyMessage.DetectRes.left_topx', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='left_topy', full_name='MyMessage.DetectRes.left_topy', index=3,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='right_bottomx', full_name='MyMessage.DetectRes.right_bottomx', index=4,
      number=5, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='right_bottomy', full_name='MyMessage.DetectRes.right_bottomy', index=5,
      number=6, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='score', full_name='MyMessage.DetectRes.score', index=6,
      number=7, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=187,
)

DESCRIPTOR.message_types_by_name['DetectRes'] = _DETECTRES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DetectRes = _reflection.GeneratedProtocolMessageType('DetectRes', (_message.Message,), {
  'DESCRIPTOR' : _DETECTRES,
  '__module__' : 'res_message_pb2'
  # @@protoc_insertion_point(class_scope:MyMessage.DetectRes)
  })
_sym_db.RegisterMessage(DetectRes)


# @@protoc_insertion_point(module_scope)
